services:
  postgres:
    image: postgres:17

    container_name: rideflow-postgres

    environment:
      POSTGRES_USER: rideflow
      POSTGRES_PASSWORD: rideflow
      POSTGRES_DB: rideflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
