.PHONY: proto

proto:
	buf generate

sqlc:
	sqlc generate

remove_tmp_files:
	git clean -fd -- .tmp    

docker-up:
	docker compose -f docker-compose.dev.yml up -d

migration-up:
	docker compose -f docker-compose.dev.yml exec -T db sh -c "goose -dir /migrations postgres \"host=localhost port=5432 user=postgres password=postgres dbname=rideflow sslmode=disable\" up"

migration-down:
	docker compose -f docker-compose.dev.yml exec -T db sh -c "goose -dir /migrations postgres \"host=localhost port=5432 user=postgres password=postgres dbname=rideflow sslmode=disable\" down"